/*
 Copyright (C) 2013-2015 by Andrea Giammarchi - @WebReflection

    Permission is hereby granted, free of charge, to any person obtaining a copy
    of this software and associated documentation files (the "Software"), to deal
    in the Software without restriction, including without limitation the rights
    to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
    copies of the Software, and to permit persons to whom the Software is
    furnished to do so, subject to the following conditions:

    The above copyright notice and this permission notice shall be included in
    all copies or substantial portions of the Software.

    THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
    IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
    FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
    AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
    LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
    OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
    THE SOFTWARE.

 picturefill - v3.0.2 - 2016-02-12
 https://scottjehl.github.io/picturefill/
 Copyright (c) 2016 https://github.com/scottjehl/picturefill/blob/master/Authors.txt; Licensed MIT
 Gecko-Picture - v1.0
 https://github.com/scottjehl/picturefill/tree/3.0/src/plugins/gecko-picture
 Firefox's early picture implementation (prior to FF41) is static and does
 not react to viewport changes. This tiny module fixes this.
 Picturefill - v3.0.2
 http://scottjehl.github.io/picturefill
 Copyright (c) 2015 https://github.com/scottjehl/picturefill/blob/master/Authors.txt;
  License: MIT
*/
(function(A){"function"===typeof define&&define.amd?define(A):A()})(function(){(function(A){"function"===typeof define&&define.amd?define(A):A()})(function(){(function(h){function r(c,a){if(!c)throw Error("Failed to construct "+a+": 1 argument required, but only 0 present.");}function g(c){if(1===c.length)return H(c[0]);for(var a=p.createDocumentFragment(),b=X.call(c),f=0;f<c.length;f++)a.appendChild(H(b[f]));return a}function H(c){return"object"===typeof c?c:p.createTextNode(c)}var y,p=h.document,
m=Object.prototype.hasOwnProperty,t=Object.defineProperty||function(c,a,b){m.call(b,"value")?c[a]=b.value:(m.call(b,"get")&&c.__defineGetter__(a,b.get),m.call(b,"set")&&c.__defineSetter__(a,b.set));return c},v=[].indexOf||function(c){for(var a=this.length;a--&&this[a]!==c;);return a},n=function(c){if(!c)throw"SyntaxError";if(a.test(c))throw"InvalidCharacterError";return c},q=function(c){var f="undefined"===typeof c.className,e=f?c.getAttribute("class")||"":c.className,d=f||"object"===typeof e;f=(d?
f?e:e.baseVal:e).replace(b,"");f.length&&J.push.apply(this,f.split(a));this._isSVG=d;this._=c};var d={get:function(){return new q(this)},set:function(){}};var b=/^\s+|\s+$/g,a=/\s+/,w=function(c,a){if(this.contains(c))a||this.remove(c);else if(void 0===a||a)a=!0,this.add(c);return!!a};var e=h.DocumentFragment&&DocumentFragment.prototype;var l=h.Node,c=(l||Element).prototype,f=h.CharacterData||l,k=f&&f.prototype,B=h.DocumentType,z=B&&B.prototype,F=(h.Element||l||h.HTMLElement).prototype;l=h.HTMLSelectElement||
p.createElement("select").constructor;for(var K=l.prototype.remove,A=h.SVGElement,J=["matches",F.matchesSelector||F.webkitMatchesSelector||F.khtmlMatchesSelector||F.mozMatchesSelector||F.msMatchesSelector||F.oMatchesSelector||function(c){var a=this.parentNode;return!!a&&-1<v.call(a.querySelectorAll(c),this)},"closest",function(c){for(var a=this,b;(b=a&&a.matches)&&!a.matches(c);)a=a.parentNode;return b?a:null},"prepend",function(){var c=this.firstChild,a=g(arguments);c?this.insertBefore(a,c):this.appendChild(a)},
"append",function(){this.appendChild(g(arguments))},"before",function(){var c=this.parentNode;c&&c.insertBefore(g(arguments),this)},"after",function(){var c=this.parentNode,a=this.nextSibling,b=g(arguments);c&&(a?c.insertBefore(b,a):c.appendChild(b))},"toggleAttribute",function(c,a){var b=this.hasAttribute(c);1<arguments.length?b&&!a?this.removeAttribute(c):a&&!b&&this.setAttribute(c,""):b?this.removeAttribute(c):this.setAttribute(c,"");return this.hasAttribute(c)},"replace",function(){this.replaceWith.apply(this,
arguments)},"replaceWith",function(){var c=this.parentNode;c&&c.replaceChild(g(arguments),this)},"remove",function(){var c=this.parentNode;c&&c.removeChild(this)}],X=J.slice,I=J.length;I;I-=2){var C=J[I-2];C in F||(F[C]=J[I-1]);"remove"!==C||K._dom4||((l.prototype[C]=function(){return 0<arguments.length?K.apply(this,arguments):F.remove.call(this)})._dom4=!0);/^(?:before|after|replace|replaceWith|remove)$/.test(C)&&(!f||C in k||(k[C]=J[I-1]),!B||C in z||(z[C]=J[I-1]));if(/^(?:append|prepend)$/.test(C))if(e)C in
e||(e[C]=J[I-1]);else try{p.createDocumentFragment().constructor.prototype[C]=J[I-1]}catch(x){}}p.createElement("a").matches("a")||(F[C]=function(c){return function(a){return c.call(this.parentNode?this:p.createDocumentFragment().appendChild(this),a)}}(F[C]));q.prototype={length:0,add:function(){for(var c=0,a;c<arguments.length;c++)a=arguments[c],this.contains(a)||J.push.call(this,C);this._isSVG?this._.setAttribute("class",""+this):this._.className=""+this},contains:function(c){return function(a){I=
c.call(this,C=n(a));return-1<I}}([].indexOf||function(c){for(I=this.length;I--&&this[I]!==c;);return I}),item:function(c){return this[c]||null},remove:function(){for(var c=0,a;c<arguments.length;c++)a=arguments[c],this.contains(a)&&J.splice.call(this,I,1);this._isSVG?this._.setAttribute("class",""+this):this._.className=""+this},toggle:w,toString:function(){return J.join.call(this," ")}};!A||"classList"in A.prototype||t(A.prototype,"classList",d);"classList"in p.documentElement?(d=p.createElement("div").classList,
d.add("a","b","a"),"a b"!=d&&(d=d.constructor.prototype,"add"in d||(d=h.TemporaryTokenList.prototype),e=function(c){return function(){for(var a=0;a<arguments.length;)c.call(this,arguments[a++])}},d.add=e(d.add),d.remove=e(d.remove),d.toggle=w)):t(F,"classList",d);"contains"in c||t(c,"contains",{value:function(c){for(;c&&c!==this;)c=c.parentNode;return this===c}});"head"in p||t(p,"head",{get:function(){return y||(y=p.getElementsByTagName("head")[0])}});(function(){for(var c,a=h.requestAnimationFrame,
b=h.cancelAnimationFrame,f=["o","ms","moz","webkit"],e=f.length;!b&&e--;)a=a||h[f[e]+"RequestAnimationFrame"],b=h[f[e]+"CancelAnimationFrame"]||h[f[e]+"CancelRequestAnimationFrame"];b||(a?(c=a,a=function(a){var b=!0;c(function(){b&&a.apply(this,arguments)});return function(){b=!1}},b=function(c){c()}):(a=function(c){return setTimeout(c,15,15)},b=function(c){clearTimeout(c)}));h.requestAnimationFrame=a;h.cancelAnimationFrame=b})();try{new h.CustomEvent("?")}catch(x){h.CustomEvent=function(c,a){function b(c,
a,b,f){this.initEvent(c,a,b);this.detail=f}return function(f,e){var d=p.createEvent(c);if("string"!=typeof f)throw Error("An event name must be provided");"Event"==c&&(d.initCustomEvent=b);null==e&&(e=a);d.initCustomEvent(f,e.bubbles,e.cancelable,e.detail);return d}}(h.CustomEvent?"CustomEvent":"Event",{bubbles:!1,cancelable:!1,detail:null})}try{new Event("_")}catch(x){x=function(c){function a(c,a){r(arguments.length,"Event");var b=p.createEvent("Event");a||(a={});b.initEvent(c,!!a.bubbles,!!a.cancelable);
return b}a.prototype=c.prototype;return a}(h.Event||function(){}),t(h,"Event",{value:x}),Event!==x&&(Event=x)}try{new KeyboardEvent("_",{})}catch(x){x=function(c){function a(c,a){r(arguments.length,"KeyboardEvent");var e=a||{},k=f;for(l in k)k.hasOwnProperty(l)&&!k.hasOwnProperty.call(e,l)&&(e[l]=k[l]);a=e;e=p.createEvent(d);k=a.ctrlKey;var l=a.shiftKey;var B=a.altKey,g=a.metaKey,n=a.altGraphKey;if(3<b){var z=a;for(var m=[],D="ctrlKey Control shiftKey Shift altKey Alt metaKey Meta altGraphKey AltGraph".split(" "),
M=0;M<D.length;M+=2)z[D[M]]&&m.push(D[M+1]);z=m.join(" ")}else z=null;m=String(a.key);var P=String(a.char);D=a.location;M=a.keyCode||(a.keyCode=m)&&m.charCodeAt(0)||0;P=a.charCode||(a.charCode=P)&&P.charCodeAt(0)||0;var G=a.bubbles,W=a.cancelable,w=a.repeat,q=a.locale,Z=a.view||h;a.which||(a.which=a.keyCode);if("initKeyEvent"in e)e.initKeyEvent(c,G,W,Z,k,B,l,g,M,P);else if(0<b&&"initKeyboardEvent"in e){G=[c,G,W,Z];switch(b){case 1:G.push(m,D,k,l,B,g,n);break;case 2:G.push(k,B,l,g,M,P);break;case 3:G.push(m,
D,k,B,l,g,n);break;case 4:G.push(m,D,z,w,q);break;default:G.push(char,m,D,z,w,q)}e.initKeyboardEvent.apply(e,G)}else e.initEvent(c,G,W);for(m in e)if(f.hasOwnProperty(m)&&e[m]!==a[m])try{e[m]=a[m]}catch(oa){}return e}var b=0,f={char:"",key:"",location:0,ctrlKey:!1,shiftKey:!1,altKey:!1,metaKey:!1,altGraphKey:!1,repeat:!1,locale:navigator.language,detail:0,bubbles:!1,cancelable:!1,keyCode:0,charCode:0,which:0};try{var e=p.createEvent("KeyboardEvent");e.initKeyboardEvent("keyup",!1,!1,h,"+",3,!0,!1,
!0,!1,!1);b="+"==(e.keyIdentifier||e.key)&&3==(e.keyLocation||e.location)&&(e.ctrlKey?e.altKey?1:3:e.shiftKey?2:4)||9}catch(ba){}var d=0<b?"KeyboardEvent":"Event";a.prototype=c.prototype;return a}(h.KeyboardEvent||function(){}),t(h,"KeyboardEvent",{value:x}),KeyboardEvent!==x&&(KeyboardEvent=x)}try{new MouseEvent("_",{})}catch(x){x=function(c){function a(c,a){r(arguments.length,"MouseEvent");var b=p.createEvent("MouseEvent");a||(a={});b.initMouseEvent(c,!!a.bubbles,!!a.cancelable,a.view||h,a.detail||
1,a.screenX||0,a.screenY||0,a.clientX||0,a.clientY||0,!!a.ctrlKey,!!a.altKey,!!a.shiftKey,!!a.metaKey,a.button||0,a.relatedTarget||null);return b}a.prototype=c.prototype;return a}(h.MouseEvent||function(){}),t(h,"MouseEvent",{value:x}),MouseEvent!==x&&(MouseEvent=x)}p.querySelectorAll("*").forEach||function(){function a(a){var c=a.querySelectorAll;a.querySelectorAll=function(a){a=c.call(this,a);a.forEach=Array.prototype.forEach;return a}}a(p);a(Element.prototype)}();try{p.querySelector(":scope *")}catch(x){(function(){function a(a,
b,f){if(a.type!=p.ELEMENT_NODE)return b.call(a,f);a.setAttribute(c,null);b=b.call(a,String(f).replace(/(^|,\s*)(:scope([ >]|$))/g,function(a,b,f,e){return b+"["+c+"]"+(e||" ")}));a.removeAttribute(c);return b}var c="data-scope-"+(1E9*Math.random()>>>0),b=Element.prototype,f=b.querySelector,e=b.querySelectorAll;b.querySelector=function(c){return a(this,f,c)};b.querySelectorAll=function(c){return a(this,e,c)}})()}})(window);(function(h){function r(){}function g(a,b,e){function d(a){d.once&&(a.currentTarget.removeEventListener(a.type,
b,d),d.removed=!0);d.passive&&(a.preventDefault=g.preventDefault);"function"===typeof d.callback?d.callback.call(this,a):d.callback&&d.callback.handleEvent(a);d.passive&&delete a.preventDefault}d.type=a;d.callback=b;d.capture=!!e.capture;d.passive=!!e.passive;d.once=!!e.once;d.removed=!1;return d}var H=h.WeakMap||function(){function a(a,b,e){f=e;c=!1;k=void 0;a.dispatchEvent(b)}function b(a){this.value=a}function e(){d++;this.__ce__=new y("@DOMMap:"+d+Math.random())}var d=0,c=!1,f=!1,k;b.prototype.handleEvent=
function(a){c=!0;f?a.currentTarget.removeEventListener(a.type,this,!1):k=this.value};e.prototype={constructor:e,"delete":function(b){return a(b,this.__ce__,!0),c},get:function(c){a(c,this.__ce__,!1);c=k;k=void 0;return c},has:function(b){return a(b,this.__ce__,!1),c},set:function(c,f){a(c,this.__ce__,!0);c.addEventListener(this.__ce__.type,new b(f),!1);return this}};return e}();r.prototype=(Object.create||Object)(null);g.preventDefault=function(){};var y=h.CustomEvent,p=h.dispatchEvent,m=h.addEventListener,
t=h.removeEventListener,v=0,n=function(){v++},q=[].indexOf||function(a){for(var b=this.length;b--&&this[b]!==a;);return b},d=function(a){return"".concat(a.capture?"1":"0",a.passive?"1":"0",a.once?"1":"0")},b;try{m("_",n,{once:!0}),p(new y("_")),p(new y("_")),t("_",n,{once:!0})}catch(a){}1!==v&&function(){function a(a){return function(c,b,k){if(k&&"boolean"!==typeof k){var f=e.get(this),h=d(k);f||e.set(this,f=new r);c in f||(f[c]={handler:[],wrap:[]});var l=f[c];f=q.call(l.handler,b);0>f?(f=l.handler.push(b)-
1,l.wrap[f]=f=new r):f=l.wrap[f];h in f||(f[h]=g(c,b,k),a.call(this,c,f[h],f[h].capture))}else a.call(this,c,b,k)}}function m(a){return function(c,b,k){if(k&&"boolean"!==typeof k){var f=e.get(this);if(f&&c in f){var h=f[c];b=q.call(h.handler,b);if(-1<b){k=d(k);var l=h.wrap[b];if(k in l){a.call(this,c,l[k],l[k].capture);delete l[k];for(k in l)return;h.handler.splice(b,1);h.wrap.splice(b,1);0===h.handler.length&&delete f[c]}}}}else a.call(this,c,b,k)}}var e=new H;b=function(b){b&&(b=b.prototype,b.addEventListener=
a(b.addEventListener),b.removeEventListener=m(b.removeEventListener))};h.EventTarget?b(EventTarget):(b(h.Text),b(h.Element||h.HTMLElement),b(h.HTMLDocument),b(h.Window||{prototype:h}),b(h.XMLHttpRequest))}()})(self);(function(h){(function(h){var g=navigator.userAgent;h.HTMLPictureElement&&/ecko/.test(g)&&g.match(/rv:(\d+)/)&&45>RegExp.$1&&addEventListener("resize",function(){var g,r=document.createElement("source"),p=function(h){var d=h.parentNode;if("PICTURE"===d.nodeName.toUpperCase()){var b=r.cloneNode();
d.insertBefore(b,d.firstElementChild);setTimeout(function(){d.removeChild(b)})}else if(!h._pfLastSize||h.offsetWidth>h._pfLastSize){h._pfLastSize=h.offsetWidth;var a=h.sizes;h.sizes+=",100vw";setTimeout(function(){h.sizes=a})}},m=function(){var h,d=document.querySelectorAll("picture \x3e img, img[srcset][sizes]");for(h=0;h<d.length;h++)p(d[h])},t=function(){clearTimeout(g);g=setTimeout(m,99)},v=h.matchMedia&&matchMedia("(orientation: landscape)"),n=function(){t();v&&v.addListener&&v.addListener(t)};
r.srcset="data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw\x3d\x3d";/^[c|i]|d$/.test(document.readyState||"")?n():document.addEventListener("DOMContentLoaded",n);return t}())})(window);(function(r,g,H){function y(a){return" "===a||"\t"===a||"\n"===a||"\f"===a||"\r"===a}function p(a,c){var b=new r.Image;b.onerror=function(){z[a]=!1;L()};b.onload=function(){z[a]=1===b.width;L()};b.src=c;return"pending"}function m(a,c){return a.res-c.res}function t(c,b){if(c&&b){var f=a.parseSet(b);
c=a.makeUrl(c);for(b=0;b<f.length;b++)if(c===a.makeUrl(f[b].url)){var e=f[b];break}}return e}function v(a,c){function b(c){if(c=c.exec(a.substring(l)))return c=c[0],l+=c.length,c}function f(){var a=!1,b,f,e,h,k={};for(h=0;h<d.length;h++){var g=d[h];var l=g[g.length-1];g=g.substring(0,g.length-1);var G=parseInt(g,10);var m=parseFloat(g);if(R.test(g)&&"w"===l){if(b||f)a=!0;0===G?a=!0:b=G}else if(da.test(g)&&"x"===l){if(b||f||e)a=!0;0>m?a=!0:f=m}else if(R.test(g)&&"h"===l){if(e||f)a=!0;0===G?a=!0:e=
G}else a=!0}a||(k.url=D,b&&(k.w=b),f&&(k.d=f),e&&(k.h=e),e||f||b||(k.d=1),1===k.d&&(c.has1x=!0),k.set=c,M.push(k))}for(var e=a.length,D,d,h,k,g,l=0,M=[];;){b(ba);if(l>=e)return M;D=b(ha);d=[];if(","===D.slice(-1))D=D.replace(ca,""),f();else for(b(fa),h="",k="in descriptor";;){g=a.charAt(l);if("in descriptor"===k)if(y(g))h&&(d.push(h),h="",k="after descriptor");else if(","===g){l+=1;h&&d.push(h);f();break}else if("("===g)h+=g,k="in parens";else if(""===g){h&&d.push(h);f();break}else h+=g;else if("in parens"===
k)if(")"===g)h+=g,k="in descriptor";else if(""===g){d.push(h);f();break}else h+=g;else if("after descriptor"===k&&!y(g))if(""===g){f();break}else k="in descriptor",--l;l+=1}}}function n(c){function b(a){return f.test(a)&&0<=parseFloat(a)||e.test(a)||"0"===a||"-0"===a||"+0"===a?!0:!1}var f=/^(?:[+-]?[0-9]+|[0-9]*\.[0-9]+)(?:[eE][+-]?[0-9]+)?(?:ch|cm|em|ex|in|mm|pc|pt|px|rem|vh|vmin|vmax|vw)$/i,e=/^calc\((?:[0-9a-z \.\+\-\*\/\(\)]+)\)$/i;var d=function(a){function c(){e&&(d.push(e),e="")}function b(){d[0]&&
(D.push(d),d=[])}for(var f,e="",d=[],D=[],h=0,k=0,g=!1;;){f=a.charAt(k);if(""===f)return c(),b(),D;if(g)"*"===f&&"/"===a[k+1]?(g=!1,k+=2,c()):k+=1;else{if(y(f))if(a.charAt(k-1)&&y(a.charAt(k-1))||!e){k+=1;continue}else if(0===h){c();k+=1;continue}else f=" ";else if("("===f)h+=1;else if(")"===f)--h;else if(","===f){c();b();k+=1;continue}else if("/"===f&&"*"===a.charAt(k+1)){g=!0;k+=2;continue}e+=f;k+=1}}}(c);var D=d.length;for(c=0;c<D;c++){var h=d[c];var k=h[h.length-1];if(b(k)){h.pop();if(0===h.length)return k;
h=h.join(" ");if(a.matchesMedia(h))return k}}return"100vw"}g.createElement("picture");var q,d,b,a={},w=!1,e=function(){},l=g.createElement("img"),c=l.getAttribute,f=l.setAttribute,k=l.removeAttribute,B=g.documentElement,z={},F={algorithm:""},K=navigator.userAgent,A=/rident/.test(K)||/ecko/.test(K)&&K.match(/rv:(\d+)/)&&35<RegExp.$1,J="currentSrc",X=/\s+\+?\d+(e\d+)?w/,I=/(\([^)]+\))?\s*(.+)/;K=r.picturefillCFG;var C=!0,x={},Q={},O=r.devicePixelRatio,E={px:1,"in":96},aa=g.createElement("a"),Y=!1,fa=
/^[ \t\n\r\u000c]+/,ba=/^[, \t\n\r\u000c]+/,ha=/^[^ \t\n\r\u000c]+/,ca=/[,]+$/,R=/^\d+$/,da=/^-?(?:[0-9]+|[0-9]*\.[0-9]+)(?:[eE][+-]?[0-9]+)?$/,S=function(a,c,b,f){a.addEventListener?a.addEventListener(c,b,f||!1):a.attachEvent&&a.attachEvent("on"+c,b)},T=function(a){var c={};return function(b){b in c||(c[b]=a(b));return c[b]}},U=function(){var a=/^([\d\.]+)(em|vw|px)$/,c=function(){for(var a=arguments,c=0,b=a[0];++c in a;)b=b.replace(a[c],a[++c]);return b},b=T(function(a){return"return "+c((a||"").toLowerCase(),
/\band\b/g,"\x26\x26",/,/g,"||",/min-([a-z-\s]+):/g,"e.$1\x3e\x3d",/max-([a-z-\s]+):/g,"e.$1\x3c\x3d",/calc([^)]+)/g,"($1)",/(\d+[\.]*[\d]*)([a-z]+)/g,"($1 * e.$2)",/^(?!(e.[a-z]|[0-9\.&=|><\+\-\*\(\)\/])).*/ig,"")+";"});return function(c,f){var e;if(!(c in x))if(x[c]=!1,f&&(e=c.match(a)))x[c]=e[1]*E[e[2]];else try{x[c]=(new Function("e",b(c)))(E)}catch(ia){}return x[c]}}(),V=function(c,b){c.w?(c.cWidth=a.calcListLength(b||"100vw"),c.res=c.w/c.cWidth):c.res=c.d;return c},L=function(c){if(w){var b,
f,e=c||{};e.elements&&1===e.elements.nodeType&&("IMG"===e.elements.nodeName.toUpperCase()?e.elements=[e.elements]:(e.context=e.elements,e.elements=null));c=e.elements||a.qsa(e.context||g,e.reevaluate||e.reselect?a.sel:a.selShort);if(f=c.length){a.setupRun(e);Y=!0;for(b=0;b<f;b++)a.fillImg(c[b],e);a.teardownRun(e)}}};r.console&&console.warn?function(a){console.warn(a)}:e;J in l||(J="src");z["image/jpeg"]=!0;z["image/gif"]=!0;z["image/png"]=!0;z["image/svg+xml"]=g.implementation.hasFeature("http://www.w3.org/TR/SVG11/feature#Image",
"1.1");a.ns=("pf"+(new Date).getTime()).substr(0,9);a.supSrcset="srcset"in l;a.supSizes="sizes"in l;a.supPicture=!!r.HTMLPictureElement;a.supSrcset&&a.supPicture&&!a.supSizes&&function(c){l.srcset="data:,a";c.src="data:,a";a.supSrcset=l.complete===c.complete;a.supPicture=a.supSrcset&&a.supPicture}(g.createElement("img"));a.supSrcset&&!a.supSizes?function(){var c=g.createElement("img"),b=function(){2===c.width&&(a.supSizes=!0);d=a.supSrcset&&!a.supSizes;w=!0;setTimeout(L)};c.onload=b;c.onerror=b;c.setAttribute("sizes",
"9px");c.srcset="data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw\x3d\x3d 1w,data:image/gif;base64,R0lGODlhAgABAPAAAP///wAAACH5BAAAAAAALAAAAAACAAEAAAICBAoAOw\x3d\x3d 9w";c.src="data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw\x3d\x3d"}():w=!0;a.selShort="picture\x3eimg,img[srcset]";a.sel=a.selShort;a.cfg=F;a.DPR=O||1;a.u=E;a.types=z;a.setSize=e;a.makeUrl=T(function(a){aa.href=a;return aa.href});a.qsa=function(a,c){return"querySelector"in a?a.querySelectorAll(c):
[]};a.matchesMedia=function(){r.matchMedia&&(matchMedia("(min-width: 0.1em)")||{}).matches?a.matchesMedia=function(a){return!a||matchMedia(a).matches}:a.matchesMedia=a.mMQ;return a.matchesMedia.apply(this,arguments)};a.mMQ=function(a){return a?U(a):!0};a.calcLength=function(a){a=U(a,!0)||!1;0>a&&(a=!1);return a};a.supportsType=function(a){return a?z[a]:!0};a.parseSize=T(function(a){a=(a||"").match(I);return{media:a&&a[1],length:a&&a[2]}});a.parseSet=function(a){a.cands||(a.cands=v(a.srcset,a));return a.cands};
a.getEmValue=function(){var a;if(!q&&(a=g.body)){var c=g.createElement("div"),b=B.style.cssText,f=a.style.cssText;c.style.cssText="position:absolute;left:0;visibility:hidden;display:block;padding:0;border:none;font-size:1em;width:1em;overflow:hidden;clip:rect(0px, 0px, 0px, 0px)";B.style.cssText="font-size:100%!important;";a.style.cssText="font-size:100%!important;";a.appendChild(c);q=c.offsetWidth;a.removeChild(c);q=parseFloat(q,10);B.style.cssText=b;a.style.cssText=f}return q||16};a.calcListLength=
function(c){if(!(c in Q)||F.uT){var b=a.calcLength(n(c));Q[c]=b?b:E.width}return Q[c]};a.setRes=function(c){if(c){var b=a.parseSet(c);for(var f=0,e=b.length;f<e;f++)V(b[f],c.sizes)}return b};a.setRes.res=V;a.applySetCandidate=function(c,b){if(c.length){var f,e,d=b[a.ns],k=a.DPR;var h=d.curSrc||b[J];if(!(f=d.curCan)){f=h;var g=c[0].set;!g&&f&&(g=(g=b[a.ns].sets)&&g[g.length-1]);if(g=t(f,g))f=a.makeUrl(f),b[a.ns].curSrc=f,b[a.ns].curCan=g,g.res||V(g,g.set.sizes);f=g}if(f&&f.set===c[0].set){var l=A&&
!b.complete&&f.res-.1>k;l||(f.cached=!0,f.res>=k&&(e=f))}if(!e){c.sort(m);var n=c.length;e=c[n-1];for(g=0;g<n;g++)if(f=c[g],f.res>=k){e=g-1;if(l=c[e]&&(l||h!==a.makeUrl(f.url)))g=c[e].res,n=f.res,"saveData"===F.algorithm?2.7<g?l=k+1:(l=Math.pow(g-.6,1.5),n=(n-k)*l,c[e].cached&&(n+=.1*l),l=g+n):l=1<k?Math.sqrt(g*n):g,l=l>k;e=l?c[e]:f;break}}e&&(c=a.makeUrl(e.url),d.curSrc=c,d.curCan=e,c!==h&&a.setSrc(b,e),a.setSize(b))}};a.setSrc=function(a,c){a.src=c.url;"image/svg+xml"===c.set.type&&(c=a.style.width,
a.style.width=a.offsetWidth+1+"px",a.offsetWidth+1&&(a.style.width=c))};a.getSet=function(c){var b,f=!1,e=c[a.ns].sets;for(c=0;c<e.length&&!f;c++){var d=e[c];if(d.srcset&&a.matchesMedia(d.media)&&(b=a.supportsType(d.type))){"pending"===b&&(d=b);f=d;break}}return f};a.parseSets=function(b,e,h){var g=e&&"PICTURE"===e.nodeName.toUpperCase(),l=b[a.ns];if(l.src===H||h.src)l.src=c.call(b,"src"),l.src?f.call(b,"data-pfsrc",l.src):k.call(b,"data-pfsrc");if(l.srcset===H||h.srcset||!a.supSrcset||b.srcset){var m=
c.call(b,"srcset");l.srcset=m;var n=!0}l.sets=[];if(g){l.pic=!0;h=l.sets;var B,z,w=e.getElementsByTagName("source");e=0;for(B=w.length;e<B;e++){var p=w[e];p[a.ns]=!0;(z=p.getAttribute("srcset"))&&h.push({srcset:z,media:p.getAttribute("media"),type:p.getAttribute("type"),sizes:p.getAttribute("sizes")})}}if(l.srcset){var q={srcset:l.srcset,sizes:c.call(b,"sizes")};l.sets.push(q);var r=(d||l.src)&&X.test(l.srcset||"");r||!l.src||t(l.src,q)||q.has1x||(q.srcset+=", "+l.src,q.cands.push({url:l.src,d:1,
set:q}))}else l.src&&l.sets.push({srcset:l.src,sizes:null});l.curCan=null;l.curSrc=H;l.supported=!(g||q&&!a.supSrcset||r&&!a.supSizes);n&&a.supSrcset&&!l.supported&&(m?(f.call(b,"data-pfsrcset",m),b.srcset=""):k.call(b,"data-pfsrcset"));l.supported&&!l.srcset&&(!l.src&&b.src||b.src!==a.makeUrl(l.src))&&(null===l.src?b.removeAttribute("src"):b.src=l.src);l.parsed=!0};a.fillImg=function(c,f){var e=f.reselect||f.reevaluate;c[a.ns]||(c[a.ns]={});var d=c[a.ns];if(e||d.evaled!==b)d.parsed&&!f.reevaluate||
a.parseSets(c,c.parentNode,f),d.supported?d.evaled=b:(d=a.getSet(c),f=!1,"pending"!==d&&(f=b,d&&(d=a.setRes(d),a.applySetCandidate(d,c))),c[a.ns].evaled=f)};a.setupRun=function(){if(!Y||C||O!==r.devicePixelRatio)C=!1,O=r.devicePixelRatio,x={},Q={},a.DPR=O||1,E.width=Math.max(r.innerWidth||0,B.clientWidth),E.height=Math.max(r.innerHeight||0,B.clientHeight),E.vw=E.width/100,E.vh=E.height/100,b=[E.height,E.width,O].join("-"),E.em=a.getEmValue(),E.rem=E.em};a.supPicture?(L=e,a.fillImg=e):function(){var c,
b=r.attachEvent?/d$|^c/:/d$|^c|^i/,f=function(){var d=g.readyState||"";e=setTimeout(f,"loading"===d?200:999);g.body&&(a.fillImgs(),(c=c||b.test(d))&&clearTimeout(e))},e=setTimeout(f,g.body?9:99),d=B.clientHeight;S(r,"resize",function(a,c){var b,f,e=function(){var d=new Date-f;d<c?b=setTimeout(e,c-d):(b=null,a())};return function(){f=new Date;b||(b=setTimeout(e,c))}}(function(){C=Math.max(r.innerWidth||0,B.clientWidth)!==E.width||B.clientHeight!==d;d=B.clientHeight;C&&a.fillImgs()},99));S(g,"readystatechange",
f)}();a.picturefill=L;a.fillImgs=L;a.teardownRun=e;L._=a;for(r.picturefillCFG={pf:a,push:function(c){var b=c.shift();"function"===typeof a[b]?a[b].apply(a,c):(F[b]=c[0],Y&&a.fillImgs({reselect:!0}))}};K&&K.length;)r.picturefillCFG.push(K.shift());r.picturefill=L;h.exports=L;a.supPicture||(z["image/webp"]=p("image/webp","data:image/webp;base64,UklGRkoAAABXRUJQVlA4WAoAAAAQAAAAAAAAAAAAQUxQSAwAAAABBxAR/Q9ERP8DAABWUDggGAAAADABAJ0BKgEAAQADADQlpAADcAD++/1QAA\x3d\x3d"))})(window,document)})({exports:{}});
(function(){function h(a){try{return a.defaultView&&a.defaultView.frameElement||null}catch(f){return null}}function r(a){this.time=a.time;this.target=a.target;this.rootBounds=v(a.rootBounds);this.boundingClientRect=v(a.boundingClientRect);this.intersectionRect=v(a.intersectionRect||t());this.isIntersecting=!!a.intersectionRect;a=this.boundingClientRect;a=a.width*a.height;var c=this.intersectionRect;c=c.width*c.height;this.intersectionRatio=a?Number((c/a).toFixed(4)):this.isIntersecting?1:0}function g(a,
b){b=b||{};if("function"!=typeof a)throw Error("callback must be a function");if(b.root&&1!=b.root.nodeType&&9!=b.root.nodeType)throw Error("root must be a Document or Element");this._checkForIntersections=H(this._checkForIntersections.bind(this),this.THROTTLE_TIMEOUT);this._callback=a;this._observationTargets=[];this._queuedEntries=[];this._rootMarginValues=this._parseRootMargin(b.rootMargin);this.thresholds=this._initThresholds(b.threshold);this.root=b.root||null;this.rootMargin=this._rootMarginValues.map(function(a){return a.value+
a.unit}).join(" ");this._monitoringDocuments=[];this._monitoringUnsubscribes=[]}function H(a,b){var c=null;return function(){c||(c=setTimeout(function(){a();c=null},b))}}function y(a,b,e,d){"function"==typeof a.addEventListener?a.addEventListener(b,e,d||!1):"function"==typeof a.attachEvent&&a.attachEvent("on"+b,e)}function p(a,b,e,d){"function"==typeof a.removeEventListener?a.removeEventListener(b,e,d||!1):"function"==typeof a.detatchEvent&&a.detatchEvent("on"+b,e)}function m(a){try{var c=a.getBoundingClientRect()}catch(k){}if(!c)return t();
c.width&&c.height||(c={top:c.top,right:c.right,bottom:c.bottom,left:c.left,width:c.right-c.left,height:c.bottom-c.top});return c}function t(){return{top:0,bottom:0,left:0,right:0,width:0,height:0}}function v(a){return!a||"x"in a?a:{top:a.top,y:a.top,bottom:a.bottom,left:a.left,x:a.left,right:a.right,width:a.width,height:a.height}}function n(a,b){var c=b.top-a.top;a=b.left-a.left;return{top:c,left:a,height:b.height,width:b.width,bottom:c+b.height,right:a+b.width}}function q(a,b){for(;b;){if(b==a)return!0;
b=d(b)}return!1}function d(c){var b=c.parentNode;if(9==c.nodeType&&c!=a)return h(c);b&&b.assignedSlot&&(b=b.assignedSlot.parentNode);return b&&11==b.nodeType&&b.host?b.host:b}function b(a){return a&&9===a.nodeType}if("object"===typeof window)if("IntersectionObserver"in window&&"IntersectionObserverEntry"in window&&"intersectionRatio"in window.IntersectionObserverEntry.prototype)"isIntersecting"in window.IntersectionObserverEntry.prototype||Object.defineProperty(window.IntersectionObserverEntry.prototype,
"isIntersecting",{get:function(){return 0<this.intersectionRatio}});else{var a=function(a){for(var c=h(a);c;)a=c.ownerDocument,c=h(a);return a}(window.document),w=[],e=null,l=null;g.prototype.THROTTLE_TIMEOUT=100;g.prototype.POLL_INTERVAL=null;g.prototype.USE_MUTATION_OBSERVER=!0;g._setupCrossOriginUpdater=function(){e||(e=function(a,b){l=a&&b?n(a,b):t();w.forEach(function(a){a._checkForIntersections()})});return e};g._resetCrossOriginUpdater=function(){l=e=null};g.prototype.observe=function(a){if(!this._observationTargets.some(function(b){return b.element==
a})){if(!a||1!=a.nodeType)throw Error("target must be an Element");this._registerInstance();this._observationTargets.push({element:a,entry:null});this._monitorIntersections(a.ownerDocument);this._checkForIntersections()}};g.prototype.unobserve=function(a){this._observationTargets=this._observationTargets.filter(function(b){return b.element!=a});this._unmonitorIntersections(a.ownerDocument);0==this._observationTargets.length&&this._unregisterInstance()};g.prototype.disconnect=function(){this._observationTargets=
[];this._unmonitorAllIntersections();this._unregisterInstance()};g.prototype.takeRecords=function(){var a=this._queuedEntries.slice();this._queuedEntries=[];return a};g.prototype._initThresholds=function(a){a=a||[0];Array.isArray(a)||(a=[a]);return a.sort().filter(function(a,b,c){if("number"!=typeof a||isNaN(a)||0>a||1<a)throw Error("threshold must be a number between 0 and 1 inclusively");return a!==c[b-1]})};g.prototype._parseRootMargin=function(a){a=(a||"0px").split(/\s+/).map(function(a){a=/^(-?\d*\.?\d+)(px|%)$/.exec(a);
if(!a)throw Error("rootMargin must be specified in pixels or percent");return{value:parseFloat(a[1]),unit:a[2]}});a[1]=a[1]||a[0];a[2]=a[2]||a[0];a[3]=a[3]||a[1];return a};g.prototype._monitorIntersections=function(b){var c=b.defaultView;if(c&&-1==this._monitoringDocuments.indexOf(b)){var e=this._checkForIntersections,d=null,g=null;this.POLL_INTERVAL?d=c.setInterval(e,this.POLL_INTERVAL):(y(c,"resize",e,!0),y(b,"scroll",e,!0),this.USE_MUTATION_OBSERVER&&"MutationObserver"in c&&(g=new c.MutationObserver(e),
g.observe(b,{attributes:!0,childList:!0,characterData:!0,subtree:!0})));this._monitoringDocuments.push(b);this._monitoringUnsubscribes.push(function(){var a=b.defaultView;a&&(d&&a.clearInterval(d),p(a,"resize",e,!0));p(b,"scroll",e,!0);g&&g.disconnect()});b!=(this.root&&(this.root.ownerDocument||this.root)||a)&&(c=h(b))&&this._monitorIntersections(c.ownerDocument)}};g.prototype._unmonitorIntersections=function(b){var c=this._monitoringDocuments.indexOf(b);if(-1!=c){var e=this.root&&(this.root.ownerDocument||
this.root)||a;if(!this._observationTargets.some(function(a){a=a.element.ownerDocument;if(a==b)return!0;for(;a&&a!=e;)if(a=(a=h(a))&&a.ownerDocument,a==b)return!0;return!1})){var d=this._monitoringUnsubscribes[c];this._monitoringDocuments.splice(c,1);this._monitoringUnsubscribes.splice(c,1);d();b!=e&&(c=h(b))&&this._unmonitorIntersections(c.ownerDocument)}}};g.prototype._unmonitorAllIntersections=function(){var a=this._monitoringUnsubscribes.slice(0);this._monitoringDocuments.length=0;for(var b=this._monitoringUnsubscribes.length=
0;b<a.length;b++)a[b]()};g.prototype._checkForIntersections=function(){if(this.root||!e||l){var a=this._rootIsInDom(),b=a?this._getRootRect():t();this._observationTargets.forEach(function(c){var d=c.element,f=m(d),h=this._rootContainsTarget(d),g=c.entry,l=a&&h&&this._computeTargetAndRootIntersection(d,f,b),k=null;if(!this._rootContainsTarget(d))k=t();else if(!e||this.root)k=b;c=c.entry=new r({time:window.performance&&performance.now&&performance.now(),target:d,boundingClientRect:f,rootBounds:k,intersectionRect:l});
g?a&&h?this._hasCrossedThreshold(g,c)&&this._queuedEntries.push(c):g&&g.isIntersecting&&this._queuedEntries.push(c):this._queuedEntries.push(c)},this);this._queuedEntries.length&&this._callback(this.takeRecords(),this)}};g.prototype._computeTargetAndRootIntersection=function(b,f,h){if("none"!=window.getComputedStyle(b).display){var c=f;f=d(b);for(b=!1;!b&&f;){var g=null,k=1==f.nodeType?window.getComputedStyle(f):{};if("none"==k.display)return null;if(f==this.root||9==f.nodeType)if(b=!0,f==this.root||
f==a)e&&!this.root?!l||0==l.width&&0==l.height?c=g=f=null:g=l:g=h;else{k=(f=d(f))&&m(f);var p=f&&this._computeTargetAndRootIntersection(f,k,h);k&&p?g=n(k,p):c=f=null}else p=f.ownerDocument,f!=p.body&&f!=p.documentElement&&"visible"!=k.overflow&&(g=m(f));if(g){k=Math.max(g.top,c.top);p=Math.min(g.bottom,c.bottom);var w=Math.max(g.left,c.left);c=Math.min(g.right,c.right);g=c-w;var q=p-k;c=0<=g&&0<=q&&{top:k,bottom:p,left:w,right:c,width:g,height:q}||null}if(!c)break;f=f&&d(f)}return c}};g.prototype._getRootRect=
function(){if(this.root&&!b(this.root))var c=m(this.root);else{var e=b(this.root)?this.root:a;c=e.documentElement;e=e.body;c={top:0,left:0,right:c.clientWidth||e.clientWidth,width:c.clientWidth||e.clientWidth,bottom:c.clientHeight||e.clientHeight,height:c.clientHeight||e.clientHeight}}return this._expandRectByRootMargin(c)};g.prototype._expandRectByRootMargin=function(a){var b=this._rootMarginValues.map(function(b,c){return"px"==b.unit?b.value:b.value*(c%2?a.width:a.height)/100});b={top:a.top-b[0],
right:a.right+b[1],bottom:a.bottom+b[2],left:a.left-b[3]};b.width=b.right-b.left;b.height=b.bottom-b.top;return b};g.prototype._hasCrossedThreshold=function(a,b){a=a&&a.isIntersecting?a.intersectionRatio||0:-1;b=b.isIntersecting?b.intersectionRatio||0:-1;if(a!==b)for(var c=0;c<this.thresholds.length;c++){var e=this.thresholds[c];if(e==a||e==b||e<a!==e<b)return!0}};g.prototype._rootIsInDom=function(){return!this.root||q(a,this.root)};g.prototype._rootContainsTarget=function(b){var c=this.root&&(this.root.ownerDocument||
this.root)||a;return q(c,b)&&(!this.root||c==b.ownerDocument)};g.prototype._registerInstance=function(){0>w.indexOf(this)&&w.push(this)};g.prototype._unregisterInstance=function(){var a=w.indexOf(this);-1!=a&&w.splice(a,1)};window.IntersectionObserver=g;window.IntersectionObserverEntry=r}})();var A={exports:{}};(function(h,r){(function(){h.exports={polyfill:function(){function g(a,b){this.scrollLeft=a;this.scrollTop=b}function h(a){if(null===a||"object"!==typeof a||void 0===a.behavior||"auto"===a.behavior||
"instant"===a.behavior)return!0;if("object"===typeof a&&"smooth"===a.behavior)return!1;throw new TypeError("behavior member of ScrollOptions "+a.behavior+" is not a valid value for enumeration ScrollBehavior.");}function r(a,b){if("Y"===b)return a.clientHeight+w<a.scrollHeight;if("X"===b)return a.clientWidth+w<a.scrollWidth}function p(a,b){a=n.getComputedStyle(a,null)["overflow"+b];return"auto"===a||"scroll"===a}function m(a){var b=r(a,"Y")&&p(a,"Y");a=r(a,"X")&&p(a,"X");return b||a}function t(b){var e=
(a()-b.startTime)/468;var c=.5*(1-Math.cos(Math.PI*(1<e?1:e)));e=b.startX+(b.x-b.startX)*c;c=b.startY+(b.y-b.startY)*c;b.method.call(b.scrollable,e,c);e===b.x&&c===b.y||n.requestAnimationFrame(t.bind(n,b))}function v(e,d,c){var f=a();if(e===q.body){var h=n;var l=n.scrollX||n.pageXOffset;e=n.scrollY||n.pageYOffset;var m=b.scroll}else h=e,l=e.scrollLeft,e=e.scrollTop,m=g;t({scrollable:h,method:m,startTime:f,startX:l,startY:e,x:d,y:c})}var n=window,q=document;if(!("scrollBehavior"in q.documentElement.style&&
!0!==n.__forceSmoothScrollPolyfill__)){var d=n.HTMLElement||n.Element,b={scroll:n.scroll||n.scrollTo,scrollBy:n.scrollBy,elementScroll:d.prototype.scroll||g,scrollIntoView:d.prototype.scrollIntoView},a=n.performance&&n.performance.now?n.performance.now.bind(n.performance):Date.now,w=/MSIE |Trident\/|Edge\//.test(n.navigator.userAgent)?1:0;n.scroll=n.scrollTo=function(a,d){void 0!==a&&(!0===h(a)?b.scroll.call(n,void 0!==a.left?a.left:"object"!==typeof a?a:n.scrollX||n.pageXOffset,void 0!==a.top?a.top:
void 0!==d?d:n.scrollY||n.pageYOffset):v.call(n,q.body,void 0!==a.left?~~a.left:n.scrollX||n.pageXOffset,void 0!==a.top?~~a.top:n.scrollY||n.pageYOffset))};n.scrollBy=function(a,d){void 0!==a&&(h(a)?b.scrollBy.call(n,void 0!==a.left?a.left:"object"!==typeof a?a:0,void 0!==a.top?a.top:void 0!==d?d:0):v.call(n,q.body,~~a.left+(n.scrollX||n.pageXOffset),~~a.top+(n.scrollY||n.pageYOffset)))};d.prototype.scroll=d.prototype.scrollTo=function(a,d){if(void 0!==a)if(!0===h(a)){if("number"===typeof a&&void 0===
d)throw new SyntaxError("Value could not be converted");b.elementScroll.call(this,void 0!==a.left?~~a.left:"object"!==typeof a?~~a:this.scrollLeft,void 0!==a.top?~~a.top:void 0!==d?~~d:this.scrollTop)}else d=a.left,a=a.top,v.call(this,this,"undefined"===typeof d?this.scrollLeft:~~d,"undefined"===typeof a?this.scrollTop:~~a)};d.prototype.scrollBy=function(a,d){void 0!==a&&(!0===h(a)?b.elementScroll.call(this,void 0!==a.left?~~a.left+this.scrollLeft:~~a+this.scrollLeft,void 0!==a.top?~~a.top+this.scrollTop:
~~d+this.scrollTop):this.scroll({left:~~a.left+this.scrollLeft,top:~~a.top+this.scrollTop,behavior:a.behavior}))};d.prototype.scrollIntoView=function(a){if(!0===h(a))b.scrollIntoView.call(this,void 0===a?!0:a);else{for(a=this;a!==q.body&&!1===m(a);)a=a.parentNode||a.host;var d=a.getBoundingClientRect(),c=this.getBoundingClientRect();a!==q.body?(v.call(this,a,a.scrollLeft+c.left-d.left,a.scrollTop+c.top-d.top),"fixed"!==n.getComputedStyle(a).position&&n.scrollBy({left:d.left,top:d.top,behavior:"smooth"})):
n.scrollBy({left:c.left,top:c.top,behavior:"smooth"})}}}}}})()})(A);A.exports.polyfill()})});
(function(A,h){"object"===typeof exports&&"undefined"!==typeof module?h():"function"===typeof define&&define.amd?define(h):h()})(this,function(){function A(d){var b=this.constructor;return this.then(function(a){return b.resolve(d()).then(function(){return a})},function(a){return b.resolve(d()).then(function(){return b.reject(a)})})}function h(){}function r(d,b){return function(){d.apply(b,arguments)}}function g(d){if(!(this instanceof g))throw new TypeError("Promises must be constructed via new");
if("function"!==typeof d)throw new TypeError("not a function");this._state=0;this._handled=!1;this._value=void 0;this._deferreds=[];v(d,this)}function H(d,b){for(;3===d._state;)d=d._value;0===d._state?d._deferreds.push(b):(d._handled=!0,g._immediateFn(function(){var a=1===d._state?b.onFulfilled:b.onRejected;if(null===a)(1===d._state?y:p)(b.promise,d._value);else{try{var h=a(d._value)}catch(e){p(b.promise,e);return}y(b.promise,h)}}))}function y(d,b){try{if(b===d)throw new TypeError("A promise cannot be resolved with itself.");
if(b&&("object"===typeof b||"function"===typeof b)){var a=b.then;if(b instanceof g){d._state=3;d._value=b;m(d);return}if("function"===typeof a){v(r(a,b),d);return}}d._state=1;d._value=b;m(d)}catch(w){p(d,w)}}function p(d,b){d._state=2;d._value=b;m(d)}function m(d){2===d._state&&0===d._deferreds.length&&g._immediateFn(function(){d._handled||g._unhandledRejectionFn(d._value)});for(var b=0,a=d._deferreds.length;b<a;b++)H(d,d._deferreds[b]);d._deferreds=null}function t(d,b,a){this.onFulfilled="function"===
typeof d?d:null;this.onRejected="function"===typeof b?b:null;this.promise=a}function v(d,b){var a=!1;try{d(function(d){a||(a=!0,y(b,d))},function(d){a||(a=!0,p(b,d))})}catch(w){a||(a=!0,p(b,w))}}var n=setTimeout;g.prototype["catch"]=function(d){return this.then(null,d)};g.prototype.then=function(d,b){var a=new this.constructor(h);H(this,new t(d,b,a));return a};g.prototype["finally"]=A;g.all=function(d){return new g(function(b,a){function h(c,d){try{if(d&&("object"===typeof d||"function"===typeof d)){var f=
d.then;if("function"===typeof f){f.call(d,function(a){h(c,a)},a);return}}e[c]=d;0===--g&&b(e)}catch(z){a(z)}}if(!d||"undefined"===typeof d.length)return a(new TypeError("Promise.all accepts an array"));var e=Array.prototype.slice.call(d);if(0===e.length)return b([]);for(var g=e.length,c=0;c<e.length;c++)h(c,e[c])})};g.resolve=function(d){return d&&"object"===typeof d&&d.constructor===g?d:new g(function(b){b(d)})};g.reject=function(d){return new g(function(b,a){a(d)})};g.race=function(d){return new g(function(b,
a){if(!d||"undefined"===typeof d.length)return a(new TypeError("Promise.race accepts an array"));for(var h=0,e=d.length;h<e;h++)g.resolve(d[h]).then(b,a)})};g._immediateFn="function"===typeof setImmediate&&function(d){setImmediate(d)}||function(d){n(d,0)};g._unhandledRejectionFn=function(d){"undefined"!==typeof console&&console&&console.warn("Possible Unhandled Promise Rejection:",d)};var q=function(){if("undefined"!==typeof self)return self;if("undefined"!==typeof window)return window;if("undefined"!==
typeof global)return global;throw Error("unable to locate global object");}();"function"!==typeof q.Promise?q.Promise=g:q.Promise.prototype["finally"]||(q.Promise.prototype["finally"]=A)});
(function(){function A(a){var b=ua.has(a);a=/^[a-z][.0-9_a-z]*-[-.0-9_a-z]*$/.test(a);return!b&&a}function h(a){var b=a.isConnected;if(void 0!==b)return b;if(ya(a))return!0;for(;a&&!(a.__CE_isImportDocument||a instanceof Document);)a=a.parentNode||(window.ShadowRoot&&a instanceof ShadowRoot?a.host:void 0);return!(!a||!(a.__CE_isImportDocument||a instanceof Document))}function r(a){var b=a.children;if(b)return Array.prototype.slice.call(b);b=[];for(a=a.firstChild;a;a=a.nextSibling)a.nodeType===Node.ELEMENT_NODE&&
b.push(a);return b}function g(a,b){for(;b&&b!==a&&!b.nextSibling;)b=b.parentNode;return b&&b!==a?b.nextSibling:null}function H(a,b,c){for(var d=a;d;){if(d.nodeType===Node.ELEMENT_NODE){var e=d;b(e);var u=e.localName;if("link"===u&&"import"===e.getAttribute("rel")){d=e.import;void 0===c&&(c=new Set);if(d instanceof Node&&!c.has(d))for(c.add(d),d=d.firstChild;d;d=d.nextSibling)H(d,b,c);d=g(a,e);continue}else if("template"===u){d=g(a,e);continue}if(e=e.__CE_shadowRoot)for(e=e.firstChild;e;e=e.nextSibling)H(e,
b,c)}d=d.firstChild?d.firstChild:g(a,d)}}function y(){var a=!(null===N||void 0===N||!N.noDocumentConstructionObserver),b=!(null===N||void 0===N||!N.shadyDomFastWalk);this.h=[];this.a=[];this.f=!1;this.shadyDomFastWalk=b;this.C=!a}function p(a,b,c,d){var e=window.ShadyDom;if(a.shadyDomFastWalk&&e&&e.inUse){if(b.nodeType===Node.ELEMENT_NODE&&c(b),b.querySelectorAll)for(a=e.nativeMethods.querySelectorAll.call(b,"*"),b=0;b<a.length;b++)c(a[b])}else H(b,c,d)}function m(a,b){a.f=!0;a.h.push(b)}function t(a,
b){a.f=!0;a.a.push(b)}function v(a,b){a.f&&p(a,b,function(b){return n(a,b)})}function n(a,b){if(a.f&&!b.__CE_patched){b.__CE_patched=!0;for(var c=0;c<a.h.length;c++)a.h[c](b);for(c=0;c<a.a.length;c++)a.a[c](b)}}function q(b,c){var d=[];p(b,c,function(a){return d.push(a)});for(c=0;c<d.length;c++){var e=d[c];1===e.__CE_state?b.connectedCallback(e):a(b,e)}}function d(a,b){var c=[];p(a,b,function(a){return c.push(a)});for(b=0;b<c.length;b++){var d=c[b];1===d.__CE_state&&a.disconnectedCallback(d)}}function b(c,
d,e){e=void 0===e?{}:e;var f=e.D,h=e.upgrade||function(b){return a(c,b)},g=[];p(c,d,function(a){c.f&&n(c,a);if("link"===a.localName&&"import"===a.getAttribute("rel")){var d=a.import;d instanceof Node&&(d.__CE_isImportDocument=!0,d.__CE_registry=document.__CE_registry);d&&"complete"===d.readyState?d.__CE_documentLoadHandled=!0:a.addEventListener("load",function(){var d=a.import;if(!d.__CE_documentLoadHandled){d.__CE_documentLoadHandled=!0;var e=new Set;f&&(f.forEach(function(a){return e.add(a)}),e.delete(d));
b(c,d,{D:e,upgrade:h})}})}else g.push(a)},f);for(d=0;d<g.length;d++)h(g[d])}function a(a,b){try{var c=b.ownerDocument,d=c.__CE_registry,f=d&&(c.defaultView||c.__CE_isImportDocument)?K(d,b.localName):void 0;if(f&&void 0===b.__CE_state){f.constructionStack.push(b);try{try{if(new f.constructorFunction!==b)throw Error("The custom element constructor did not produce the element being upgraded.");}finally{f.constructionStack.pop()}}catch(ma){throw b.__CE_state=2,ma;}b.__CE_state=1;b.__CE_definition=f;if(f.attributeChangedCallback&&
b.hasAttributes()){var g=f.observedAttributes;for(f=0;f<g.length;f++){var u=g[f],k=b.getAttribute(u);null!==k&&a.attributeChangedCallback(b,u,null,k,null)}}h(b)&&a.connectedCallback(b)}}catch(ma){e(ma)}}function w(a,b,c,d){var f=b.__CE_registry;if(f&&(null===d||"http://www.w3.org/1999/xhtml"===d)&&(f=K(f,c)))try{var h=new f.constructorFunction;if(void 0===h.__CE_state||void 0===h.__CE_definition)throw Error("Failed to construct '"+c+"': The returned value was not constructed with the HTMLElement constructor.");
if("http://www.w3.org/1999/xhtml"!==h.namespaceURI)throw Error("Failed to construct '"+c+"': The constructed element's namespace must be the HTML namespace.");if(h.hasAttributes())throw Error("Failed to construct '"+c+"': The constructed element must not have any attributes.");if(null!==h.firstChild)throw Error("Failed to construct '"+c+"': The constructed element must not have any children.");if(null!==h.parentNode)throw Error("Failed to construct '"+c+"': The constructed element must not have a parent node.");
if(h.ownerDocument!==b)throw Error("Failed to construct '"+c+"': The constructed element's owner document is incorrect.");if(h.localName!==c)throw Error("Failed to construct '"+c+"': The constructed element's local name is incorrect.");return h}catch(la){return e(la),b=null===d?O.call(b,c):E.call(b,d,c),Object.setPrototypeOf(b,HTMLUnknownElement.prototype),b.__CE_state=2,b.__CE_definition=void 0,n(a,b),b}b=null===d?O.call(b,c):E.call(b,d,c);n(a,b);return b}function e(a){var b=a.message,c=a.sourceURL||
a.fileName||"",d=a.line||a.lineNumber||0,e=a.column||a.columnNumber||0,f=void 0;void 0===ErrorEvent.prototype.initErrorEvent?f=new ErrorEvent("error",{cancelable:!0,message:b,filename:c,lineno:d,colno:e,error:a}):(f=document.createEvent("ErrorEvent"),f.initErrorEvent("error",!1,!0,b,c,d),f.preventDefault=function(){Object.defineProperty(this,"defaultPrevented",{configurable:!0,get:function(){return!0}})});void 0===f.error&&Object.defineProperty(f,"error",{configurable:!0,enumerable:!0,get:function(){return a}});
window.dispatchEvent(f);f.defaultPrevented||console.error(a)}function l(){var a=this;this.a=void 0;this.w=new Promise(function(b){a.g=b})}function c(a){var c=document;this.g=void 0;this.b=a;this.a=c;b(this.b,this.a);"loading"===this.a.readyState&&(this.g=new MutationObserver(this.A.bind(this)),this.g.observe(this.a,{childList:!0,subtree:!0}))}function f(a){a.g&&a.g.disconnect()}function k(a){this.j=new Map;this.l=new Map;this.u=new Map;this.o=!1;this.s=new Map;this.i=function(a){return a()};this.c=
!1;this.m=[];this.b=a;this.v=a.C?new c(a):void 0}function B(a,b){if(!A(b))throw new SyntaxError("The element name '"+b+"' is not valid.");if(K(a,b))throw Error("A custom element with name '"+(b+"' has already been defined."));if(a.o)throw Error("A custom element is already being defined.");}function z(a,b,c){a.o=!0;var d;try{var e=c.prototype;if(!(e instanceof Object))throw new TypeError("The custom element constructor's prototype is not an object.");var f=function(a){var b=e[a];if(void 0!==b&&!(b instanceof
Function))throw Error("The '"+a+"' callback must be a function.");return b},h=f("connectedCallback"),g=f("disconnectedCallback"),u=f("adoptedCallback"),k=(d=f("attributeChangedCallback"))&&c.observedAttributes||[]}catch(Ba){throw Ba;}finally{a.o=!1}c={localName:b,constructorFunction:c,connectedCallback:h,disconnectedCallback:g,adoptedCallback:u,attributeChangedCallback:d,observedAttributes:k,constructionStack:[]};a.l.set(b,c);a.u.set(c.constructorFunction,c);return c}function F(c){if(!1!==c.c){c.c=
!1;for(var d=[],e=c.m,f=new Map,h=0;h<e.length;h++)f.set(e[h],[]);b(c.b,document,{upgrade:function(a){if(void 0===a.__CE_state){var b=a.localName,e=f.get(b);e?e.push(a):c.l.has(b)&&d.push(a)}}});for(h=0;h<d.length;h++)a(c.b,d[h]);for(h=0;h<e.length;h++){for(var g=e[h],k=f.get(g),u=0;u<k.length;u++)a(c.b,k[u]);(g=c.s.get(g))&&g.resolve(void 0)}e.length=0}}function K(a,b){var c=a.l.get(b);if(c)return c;if(c=a.j.get(b)){a.j.delete(b);try{return z(a,b,c())}catch(Aa){e(Aa)}}}function ea(a,b,c){function e(b){return function(c){for(var e=
[],f=0;f<arguments.length;++f)e[f]=arguments[f];f=[];for(var g=[],k=0;k<e.length;k++){var u=e[k];u instanceof Element&&h(u)&&g.push(u);if(u instanceof DocumentFragment)for(u=u.firstChild;u;u=u.nextSibling)f.push(u);else f.push(u)}b.apply(this,e);for(e=0;e<g.length;e++)d(a,g[e]);if(h(this))for(e=0;e<f.length;e++)g=f[e],g instanceof Element&&q(a,g)}}void 0!==c.prepend&&(b.prepend=e(c.prepend));void 0!==c.append&&(b.append=e(c.append))}function J(a){Document.prototype.createElement=function(b){return w(a,
this,b,null)};Document.prototype.importNode=function(c,d){c=aa.call(this,c,!!d);this.__CE_registry?b(a,c):v(a,c);return c};Document.prototype.createElementNS=function(b,c){return w(a,this,c,b)};ea(a,Document.prototype,{prepend:Y,append:fa})}function X(a){function b(b){return function(c){for(var e=[],f=0;f<arguments.length;++f)e[f]=arguments[f];f=[];for(var g=[],k=0;k<e.length;k++){var u=e[k];u instanceof Element&&h(u)&&g.push(u);if(u instanceof DocumentFragment)for(u=u.firstChild;u;u=u.nextSibling)f.push(u);
else f.push(u)}b.apply(this,e);for(e=0;e<g.length;e++)d(a,g[e]);if(h(this))for(e=0;e<f.length;e++)g=f[e],g instanceof Element&&q(a,g)}}var c=Element.prototype;void 0!==qa&&(c.before=b(qa));void 0!==wa&&(c.after=b(wa));void 0!==pa&&(c.replaceWith=function(b){for(var c=[],e=0;e<arguments.length;++e)c[e]=arguments[e];e=[];for(var f=[],g=0;g<c.length;g++){var k=c[g];k instanceof Element&&h(k)&&f.push(k);if(k instanceof DocumentFragment)for(k=k.firstChild;k;k=k.nextSibling)e.push(k);else e.push(k)}g=h(this);
pa.apply(this,c);for(c=0;c<f.length;c++)d(a,f[c]);if(g)for(d(a,this),c=0;c<e.length;c++)f=e[c],f instanceof Element&&q(a,f)});void 0!==ra&&(c.remove=function(){var b=h(this);ra.call(this);b&&d(a,this)})}function I(a){function c(c,d){Object.defineProperty(c,"innerHTML",{enumerable:d.enumerable,configurable:!0,get:d.get,set:function(c){var e=this,f=void 0;h(this)&&(f=[],p(a,this,function(a){a!==e&&f.push(a)}));d.set.call(this,c);if(f)for(var g=0;g<f.length;g++){var k=f[g];1===k.__CE_state&&a.disconnectedCallback(k)}this.ownerDocument.__CE_registry?
b(a,this):v(a,this);return c}})}function e(b,c){b.insertAdjacentElement=function(b,e){var f=h(e);b=c.call(this,b,e);f&&d(a,e);h(b)&&q(a,e);return b}}function f(c,d){function e(c,d){for(var e=[];c!==d;c=c.nextSibling)e.push(c);for(d=0;d<e.length;d++)b(a,e[d])}c.insertAdjacentHTML=function(a,b){a=a.toLowerCase();if("beforebegin"===a){var c=this.previousSibling;d.call(this,a,b);e(c||this.parentNode.firstChild,this)}else if("afterbegin"===a)c=this.firstChild,d.call(this,a,b),e(this.firstChild,c);else if("beforeend"===
a)c=this.lastChild,d.call(this,a,b),e(c||this.firstChild,null);else if("afterend"===a)c=this.nextSibling,d.call(this,a,b),e(this.nextSibling,c);else throw new SyntaxError("The value provided ("+String(a)+") is not one of 'beforebegin', 'afterbegin', 'beforeend', or 'afterend'.");}}V&&(Element.prototype.attachShadow=function(b){b=V.call(this,b);if(a.f&&!b.__CE_patched){b.__CE_patched=!0;for(var c=0;c<a.h.length;c++)a.h[c](b)}return this.__CE_shadowRoot=b});L&&L.get?c(Element.prototype,L):ja&&ja.get?
c(HTMLElement.prototype,ja):t(a,function(a){c(a,{enumerable:!0,configurable:!0,get:function(){return ca.call(this,!0).innerHTML},set:function(a){var b="template"===this.localName,c=b?this.content:this,d=E.call(document,this.namespaceURI,this.localName);for(d.innerHTML=a;0<c.childNodes.length;)S.call(c,c.childNodes[0]);for(a=b?d.content:d;0<a.childNodes.length;)R.call(c,a.childNodes[0])}})});Element.prototype.setAttribute=function(b,c){if(1!==this.__CE_state)return M.call(this,b,c);var d=D.call(this,
b);M.call(this,b,c);c=D.call(this,b);a.attributeChangedCallback(this,b,d,c,null)};Element.prototype.setAttributeNS=function(b,c,d){if(1!==this.__CE_state)return W.call(this,b,c,d);var e=G.call(this,b,c);W.call(this,b,c,d);d=G.call(this,b,c);a.attributeChangedCallback(this,c,e,d,b)};Element.prototype.removeAttribute=function(b){if(1!==this.__CE_state)return P.call(this,b);var c=D.call(this,b);P.call(this,b);null!==c&&a.attributeChangedCallback(this,b,c,null,null)};Element.prototype.removeAttributeNS=
function(b,c){if(1!==this.__CE_state)return na.call(this,b,c);var d=G.call(this,b,c);na.call(this,b,c);var e=G.call(this,b,c);d!==e&&a.attributeChangedCallback(this,c,d,e,b)};sa?e(HTMLElement.prototype,sa):ia&&e(Element.prototype,ia);ta?f(HTMLElement.prototype,ta):Z&&f(Element.prototype,Z);ea(a,Element.prototype,{prepend:oa,append:za});X(a)}function C(a){function b(){var b=this.constructor,c=document.__CE_registry.u.get(b);if(!c)throw Error("Failed to construct a custom element: The constructor was not registered with `customElements`.");
var d=c.constructionStack;if(0===d.length)return d=O.call(document,c.localName),Object.setPrototypeOf(d,b.prototype),d.__CE_state=1,d.__CE_definition=c,n(a,d),d;var e=d.length-1,f=d[e];if(f===va)throw Error("Failed to construct '"+c.localName+"': This element was already constructed.");d[e]=va;Object.setPrototypeOf(f,b.prototype);n(a,f);return f}b.prototype=xa.prototype;Object.defineProperty(HTMLElement.prototype,"constructor",{writable:!0,configurable:!0,enumerable:!1,value:b});window.HTMLElement=
b}function x(a){function c(b,c){Object.defineProperty(b,"textContent",{enumerable:c.enumerable,configurable:!0,get:c.get,set:function(b){if(this.nodeType===Node.TEXT_NODE)c.set.call(this,b);else{var e=void 0;if(this.firstChild){var f=this.childNodes,g=f.length;if(0<g&&h(this)){e=Array(g);for(var k=0;k<g;k++)e[k]=f[k]}}c.set.call(this,b);if(e)for(b=0;b<e.length;b++)d(a,e[b])}}})}Node.prototype.insertBefore=function(b,c){if(b instanceof DocumentFragment){var e=r(b);b=da.call(this,b,c);if(h(this))for(c=
0;c<e.length;c++)q(a,e[c]);return b}e=b instanceof Element&&h(b);c=da.call(this,b,c);e&&d(a,b);h(this)&&q(a,b);return c};Node.prototype.appendChild=function(b){if(b instanceof DocumentFragment){var c=r(b);b=R.call(this,b);if(h(this))for(var e=0;e<c.length;e++)q(a,c[e]);return b}c=b instanceof Element&&h(b);e=R.call(this,b);c&&d(a,b);h(this)&&q(a,b);return e};Node.prototype.cloneNode=function(c){c=ca.call(this,!!c);this.ownerDocument.__CE_registry?b(a,c):v(a,c);return c};Node.prototype.removeChild=
function(b){var c=b instanceof Element&&h(b),e=S.call(this,b);c&&d(a,b);return e};Node.prototype.replaceChild=function(b,c){if(b instanceof DocumentFragment){var e=r(b);b=T.call(this,b,c);if(h(this))for(d(a,c),c=0;c<e.length;c++)q(a,e[c]);return b}e=b instanceof Element&&h(b);var f=T.call(this,b,c),g=h(this);g&&d(a,c);e&&d(a,b);g&&q(a,b);return f};U&&U.get?c(Node.prototype,U):m(a,function(a){c(a,{enumerable:!0,configurable:!0,get:function(){for(var a=[],b=this.firstChild;b;b=b.nextSibling)b.nodeType!==
Node.COMMENT_NODE&&a.push(b.textContent);return a.join("")},set:function(a){for(;this.firstChild;)S.call(this,this.firstChild);null!=a&&""!==a&&R.call(this,document.createTextNode(a))}})})}function Q(){var a=new y;C(a);J(a);ea(a,DocumentFragment.prototype,{prepend:ba,append:ha});x(a);I(a);a=new k(a);document.__CE_registry=a;Object.defineProperty(window,"customElements",{configurable:!0,enumerable:!0,value:a})}var O=window.Document.prototype.createElement,E=window.Document.prototype.createElementNS,
aa=window.Document.prototype.importNode,Y=window.Document.prototype.prepend,fa=window.Document.prototype.append,ba=window.DocumentFragment.prototype.prepend,ha=window.DocumentFragment.prototype.append,ca=window.Node.prototype.cloneNode,R=window.Node.prototype.appendChild,da=window.Node.prototype.insertBefore,S=window.Node.prototype.removeChild,T=window.Node.prototype.replaceChild,U=Object.getOwnPropertyDescriptor(window.Node.prototype,"textContent"),V=window.Element.prototype.attachShadow,L=Object.getOwnPropertyDescriptor(window.Element.prototype,
"innerHTML"),D=window.Element.prototype.getAttribute,M=window.Element.prototype.setAttribute,P=window.Element.prototype.removeAttribute,G=window.Element.prototype.getAttributeNS,W=window.Element.prototype.setAttributeNS,na=window.Element.prototype.removeAttributeNS,ia=window.Element.prototype.insertAdjacentElement,Z=window.Element.prototype.insertAdjacentHTML,oa=window.Element.prototype.prepend,za=window.Element.prototype.append,qa=window.Element.prototype.before,wa=window.Element.prototype.after,
pa=window.Element.prototype.replaceWith,ra=window.Element.prototype.remove,xa=window.HTMLElement,ja=Object.getOwnPropertyDescriptor(window.HTMLElement.prototype,"innerHTML"),sa=window.HTMLElement.prototype.insertAdjacentElement,ta=window.HTMLElement.prototype.insertAdjacentHTML,ua=new Set;"annotation-xml color-profile font-face font-face-src font-face-uri font-face-format font-face-name missing-glyph".split(" ").forEach(function(a){return ua.add(a)});var ya=document.contains?document.contains.bind(document):
document.documentElement.contains.bind(document.documentElement);y.prototype.connectedCallback=function(a){var b=a.__CE_definition;if(b.connectedCallback)try{b.connectedCallback.call(a)}catch(ka){e(ka)}};y.prototype.disconnectedCallback=function(a){var b=a.__CE_definition;if(b.disconnectedCallback)try{b.disconnectedCallback.call(a)}catch(ka){e(ka)}};y.prototype.attributeChangedCallback=function(a,b,c,d,f){var g=a.__CE_definition;if(g.attributeChangedCallback&&-1<g.observedAttributes.indexOf(b))try{g.attributeChangedCallback.call(a,
b,c,d,f)}catch(la){e(la)}};l.prototype.resolve=function(a){if(this.a)throw Error("Already resolved.");this.a=a;this.g(a)};c.prototype.A=function(a){var c=this.a.readyState;"interactive"!==c&&"complete"!==c||f(this);for(c=0;c<a.length;c++)for(var d=a[c].addedNodes,e=0;e<d.length;e++)b(this.b,d[e])};k.prototype.B=function(a,b){var c=this;if(!(b instanceof Function))throw new TypeError("Custom element constructor getters must be functions.");B(this,a);this.j.set(a,b);this.m.push(a);this.c||(this.c=!0,
this.i(function(){return F(c)}))};k.prototype.define=function(a,b){var c=this;if(!(b instanceof Function))throw new TypeError("Custom element constructors must be functions.");B(this,a);z(this,a,b);this.m.push(a);this.c||(this.c=!0,this.i(function(){return F(c)}))};k.prototype.upgrade=function(a){b(this.b,a)};k.prototype.get=function(a){if(a=K(this,a))return a.constructorFunction};k.prototype.whenDefined=function(a){if(!A(a))return Promise.reject(new SyntaxError("'"+a+"' is not a valid custom element name."));
var b=this.s.get(a);if(b)return b.w;b=new l;this.s.set(a,b);var c=this.l.has(a)||this.j.has(a);a=-1===this.m.indexOf(a);c&&a&&b.resolve(void 0);return b.w};k.prototype.polyfillWrapFlushCallback=function(a){this.v&&f(this.v);var b=this.i;this.i=function(c){return a(function(){return b(c)})}};window.CustomElementRegistry=k;k.prototype.define=k.prototype.define;k.prototype.upgrade=k.prototype.upgrade;k.prototype.get=k.prototype.get;k.prototype.whenDefined=k.prototype.whenDefined;k.prototype.polyfillDefineLazy=
k.prototype.B;k.prototype.polyfillWrapFlushCallback=k.prototype.polyfillWrapFlushCallback;var va={},N=window.customElements;N&&!N.forcePolyfill&&"function"==typeof N.define&&"function"==typeof N.get||Q();window.__CE_installPolyfill=Q}).call(self);
(function(){function A(b,a){this.scrollLeft=b;this.scrollTop=a}function h(b){if(null===b||"object"!==typeof b||void 0===b.behavior||"auto"===b.behavior||"instant"===b.behavior)return!0;if("object"===typeof b&&"smooth"===b.behavior)return!1;throw new TypeError("behavior member of ScrollOptions "+b.behavior+" is not a valid value for enumeration ScrollBehavior.");}function r(b,a){if("Y"===a)return b.clientHeight+d<b.scrollHeight;if("X"===a)return b.clientWidth+d<b.scrollWidth}function g(b,a){b=m.getComputedStyle(b,
null)["overflow"+a];return"auto"===b||"scroll"===b}function H(b){var a=r(b,"Y")&&g(b,"Y");b=r(b,"X")&&g(b,"X");return a||b}function y(b){var a=(q()-b.startTime)/468;var d=.5*(1-Math.cos(Math.PI*(1<a?1:a)));a=b.startX+(b.x-b.startX)*d;d=b.startY+(b.y-b.startY)*d;b.method.call(b.scrollable,a,d);a===b.x&&d===b.y||m.requestAnimationFrame(y.bind(m,b))}function p(b,a,d){var e=q();if(b===t.body){var g=m;var c=m.scrollX||m.pageXOffset;b=m.scrollY||m.pageYOffset;var f=n.scroll}else g=b,c=b.scrollLeft,b=b.scrollTop,
f=A;y({scrollable:g,method:f,startTime:e,startX:c,startY:b,x:a,y:d})}var m=window,t=document;if(!("scrollBehavior"in t.documentElement.style&&!0!==m.__forceSmoothScrollPolyfill__)){var v=m.HTMLElement||m.Element,n={scroll:m.scroll||m.scrollTo,scrollBy:m.scrollBy,elementScroll:v.prototype.scroll||A,scrollIntoView:v.prototype.scrollIntoView},q=m.performance&&m.performance.now?m.performance.now.bind(m.performance):Date.now,d=/MSIE |Trident\/|Edge\//.test(m.navigator.userAgent)?1:0;m.scroll=m.scrollTo=
function(b,a){void 0!==b&&(!0===h(b)?n.scroll.call(m,void 0!==b.left?b.left:"object"!==typeof b?b:m.scrollX||m.pageXOffset,void 0!==b.top?b.top:void 0!==a?a:m.scrollY||m.pageYOffset):p.call(m,t.body,void 0!==b.left?~~b.left:m.scrollX||m.pageXOffset,void 0!==b.top?~~b.top:m.scrollY||m.pageYOffset))};m.scrollBy=function(b,a){void 0!==b&&(h(b)?n.scrollBy.call(m,void 0!==b.left?b.left:"object"!==typeof b?b:0,void 0!==b.top?b.top:void 0!==a?a:0):p.call(m,t.body,~~b.left+(m.scrollX||m.pageXOffset),~~b.top+
(m.scrollY||m.pageYOffset)))};v.prototype.scroll=v.prototype.scrollTo=function(b,a){if(void 0!==b)if(!0===h(b)){if("number"===typeof b&&void 0===a)throw new SyntaxError("Value could not be converted");n.elementScroll.call(this,void 0!==b.left?~~b.left:"object"!==typeof b?~~b:this.scrollLeft,void 0!==b.top?~~b.top:void 0!==a?~~a:this.scrollTop)}else a=b.left,b=b.top,p.call(this,this,"undefined"===typeof a?this.scrollLeft:~~a,"undefined"===typeof b?this.scrollTop:~~b)};v.prototype.scrollBy=function(b,
a){void 0!==b&&(!0===h(b)?n.elementScroll.call(this,void 0!==b.left?~~b.left+this.scrollLeft:~~b+this.scrollLeft,void 0!==b.top?~~b.top+this.scrollTop:~~a+this.scrollTop):this.scroll({left:~~b.left+this.scrollLeft,top:~~b.top+this.scrollTop,behavior:b.behavior}))};v.prototype.scrollIntoView=function(b){if(!0===h(b))n.scrollIntoView.call(this,void 0===b?!0:b);else{for(b=this;b!==t.body&&!1===H(b);)b=b.parentNode||b.host;var a=b.getBoundingClientRect(),d=this.getBoundingClientRect();b!==t.body?(p.call(this,
b,b.scrollLeft+d.left-a.left,b.scrollTop+d.top-a.top),"fixed"!==m.getComputedStyle(b).position&&m.scrollBy({left:a.left,top:a.top,behavior:"smooth"})):m.scrollBy({left:d.left,top:d.top,behavior:"smooth"})}}}})();